### ISSUE TITLE
Setting wallpaper failed

### ISSUE THREAD

**Issue by kashanico** [liaoheng/BingWallpaper#13]
After a day of working correctly now I'm getting the error, setting wallpaper failed. Manually or automatic.
I looked at the debug log and it was empty. 
I've cleared both caches and still the same issue. 

I have a GS10 on Android 10
![Screenshot_20200808-111245_Starth Bing Wallpaper](https://user-images.githubusercontent.com/64927104/89717155-728eaa80-d968-11ea-8074-b4d56ab88b03.jpg)

**Comment by 0kommanix** [comment]
I had the same issue on my Galaxy Tab A 10.1 (2019) running OneUI 2,0 (same as S10 I guess). After debugging it turned out that the connection failed. Doing some further research, I found out that if your phone/tablet is connected to a 5 GHz WiFi, the WiFi gets disabled 15 minutes after the screen is off. Strangely, this doesn't happen to be the case if you're connect to 2.4 GHz but I haven't verified this.

My workaround: I am turning on the screen with MacroDroid, 1 minute before I set BingWallpaper to Update the wallpaper (Timer Mode). This way, the WiFi connection gets restored and the update has been successful since.

@liaoheng for this workaround necessary on Samsung devices, it would help if your app would expose a "wallpaper update" activity. This way I could trigger the update after taking care of restoring the WFi connection from within MacroDroid or Tasker or any other automation app. Another workaround could be to have an option to trigger the screen from within your app but I guess this is so specific to Samsung devices that probably only a small user base would profit and most users probably get confused.

**Comment by kashanico** [comment]
Funny thing. Automatic worked fine today.

**Comment by liaoheng** [comment]
@kashanico Sometimes this problem occurs, you can try to clear the cache and turn on the "DoH" option.

**Comment by liaoheng** [comment]
@0kommanix Due to system restrictions, the application cannot perform the update operation on time. in fact, there will be a delay in updating the wallpaper in the "Scheduler" mode, or use the "live wallpaper" mode for lower delay, they can all update the wallpaper normally while you are using the device.
